version: '3.8'
services:
  webapp:
    image: node:18-alpine
    container_name: chameleon_webapp
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://api:3000
    command: >
      /bin/sh -c "
        git clone https://github.com/Gizmo091/game_chameleon /usr/src/app &&
        cd /usr/src/app/webapp &&
        npm install &&
        npm run serve -- --host 0.0.0.0 --port 80
      "
networks:
  default:
    external: false